#!/bin/sh
INTERFACE=$1
STATUS=$2

IF_ETH=eno1
IPV4_DEV=eno1
ISATAP_ROUTER=210.34.219.49
XMU_IPV6_PREFIX=2001:da8:e800:45c0:200:5efe

LANG=en

setup_ipv6()
{
	localip=`ifconfig $IPV4_DEV |grep "inet "|awk '{print $2}'`
	sit_name=`ifconfig sit1|grep IPv6-in-IPv4|awk '{print $1}'
	if [ "$sit_name" = "sit" ]; then
		ip tunnel del sit1
	fi
	ip tunnel add sit1 mode isatap remote $ISATAP_ROUTER local $localip
	ip link set sit1 up
	ip tunnel prl prl-default $ISATAP_ROUTER dev sit1
	ip -6 route add default via fe80::5efe:$ISATAP_ROUTER dev sit1
	ifconfig sit1 add $XMU_IPV6_PREFIX:$localip/64
}

#start ip up
if [[ "$STATUS" =="up" && ( "$INTERFACE" == "$IF_ETH ) ]]; then
	setup_ipv6
fi

